### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by GeorgeHulpoi** [NaturalIntelligence/bexp#1]
```
const BexpParser = require("bexp");

bexpParser = new BexpParser("a and b or c but !d");
BexpParser.test("a")
BexpParser.test(["a","b"])
```

```
λ node -v
v12.22.0
```

```
BexpParser.test("a")
           ^

TypeError: BexpParser.test is not a function
    at Object.<anonymous> (D:\temp\main.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by amitguptagwl** [comment]
You're using Class instead of it's instance to call a method

```js
const BexpParser = require("bexp");

const bexpParser = new BexpParser("a and b or c but !d");
bexpParser.test("a")
bexpParser.test(["a","b"])
```

**Comment by GeorgeHulpoi** [comment]
![image](https://user-images.githubusercontent.com/7074307/120918921-a5581b00-c6bf-11eb-8785-e19e8467639f.png)

you better update the page?

**Comment by amitguptagwl** [comment]
@GeorgeHulpoi done
